### ISSUE TITLE
Checkout Specific Commit?

### ISSUE THREAD

**Issue by epmills** [symmetree-labs/zerostash#152] opened 2023-04-15 01:48 UTC
It appears that with at least v0.5.0 `0s checkout` has no option to restore files from a specific commit.  Instead, any file ever committed will be restored.

Is there a plan for something along the lines of `0s checkout --commit 123456` (ala git) to retrieve only those files stored as part of that commit?  It seems plausible because Infinitree [supports versioning](https://github.com/symmetree-labs/infinitree#versioning)?

Thanks in advance and for the great work (very excited about zerostash).

P.S.  Along the same lines, modifying a file and re-committing creates a second, identical entry in the `ls` listing but only the original version is restored upon checkout.  See lines 34 and 51 of the attached screenshot.  Just looking for clarification on expected behavior.

![term-session-0s](https://user-images.githubusercontent.com/43226824/232221451-c6955561-db38-470d-9e8d-e965876223bb.png)

**Comment by rsdy** [comment] 2023-04-16 11:19
Hey!

Thanks for the feedback. I have been meaning to implement something similar to what you're proposing, but haven't been able to due to lack of time. I should have some bandwidth for this in the coming weeks though.

The bug you've noticed is quite peculiar, and I've not run into it, but I was able to reproduce it. Will investigate further, thanks for flagging it up!

**Comment by epmills** [comment] 2023-04-16 17:08
Exciting news on possibly tackling the new functionality.  And I hope you're able to track down the root cause of the bug.
If you'd like me to test anything as an "external" user, I'm happy to help.
Thanks for the time and attention!

**Comment by rsdy** [comment] 2023-04-21 09:09
I have an update here: It seems like what happens is that we restore the file 2x, so you get an older version of it. This is because of a memory use optimization that `checkout` and `ls` use, which doesn't correctly follow the semantics of the versioned database. I'll need some more time to properly test & fix this, but at least I understand the scope, and why it didn't pop up in my test cases.

**Comment by epmills** [comment] 2023-04-21 13:10
Thanks for investigating and I'm glad you're zeroing in!

Not being a Rust expert, I'm curious why `checkout` and `ls` wouldn't use `stash.commit_list()` like `log` to use as a starting point?  Is there a way to get a list of files belonging to a specific commit?

**Comment by rsdy** [comment] 2023-05-01 18:34
@epmills I had some time to pull this together, and 0.6 should have what you need under `--commit-id`. Please let me know if this works for you!

I think the bug you run into should also be fixed with the latest release.

**Comment by epmills** [comment] 2023-05-04 04:49
Sorry I have not gotten back to you in a couple days.

Good news: I've tested v0.6.0 repeatedly and executing a check-out on a specific commit ID working great.
I'm finishing up a shell script that automates the testing using a temporary stash that is created and destroyed on the fly.  I'll share this when it's complete in a day or so.

**Comment by epmills** [comment] 2023-05-04 13:01
Here's a [basic regression script](https://gitlab.com/-/snippets/2537093) I wrote to validate v0.6.0 along with some sample output.
If you find any parts of it helpful please copy pasta and adapt at will. :)

**Comment by epmills** [comment] 2023-05-07 17:14
My testing would indicate that [v0.6.0](https://github.com/symmetree-labs/zerostash/releases/tag/v0.6.0) via [PR151](https://github.com/symmetree-labs/zerostash/pull/151) fixes this issue.

**Comment by rsdy** [comment] 2023-05-08 13:23
I'll close it then. Thanks for reporting!

**Closed as completed by rsdy** 2023-05-08 13:23 UTC
